version: '3.9'

services:
  kedro_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/home/kedro_docker/data  # Mount local data to container
    working_dir: /home/kedro_docker
    command: kedro run
