from kedro.pipeline import Pipeline, node, pipeline

from .nodes import (
    create_clients_to_remove,
    create_master_industrial,
    create_master_monthly_tct_trx,
    create_master_patentes,
    create_master_planta_industrial,
    create_master_rubro_industrial,
    create_master_total_industrial,
    create_master_transactions,
    create_master_transactions_channel,
    create_master_trx_customer_tct,
    create_master_year_channel_trx,
    create_master_year_network_trx,
    create_master_year_region_channel_trx,
    create_master_yearly_station_tct_trx,
    create_spine_clientes,
    preprocess_columns,
    process_base_cupon_electronico,
    process_base_empresas,
    process_base_industrial,
    process_base_tae_tct,
    process_competitiveness_index,
    process_maestro_data,
)


def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            node(
                func=preprocess_columns,
                inputs="raw_base_cupon_electronico",
                outputs="int_base_cupon_electronico",
                name="preprocess_base_cupon_electronico",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_base_tct_tae",
                outputs="int_base_tct_tae",
                name="preprocess_base_tct_tae",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_base_empresas",
                outputs="int_base_empresas",
                name="preprocess_base_empresas",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_contratos_tct",
                outputs="int_contratos_tct",
                name="preprocess_contratos_tct",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_contratos_tae",
                outputs="int_contratos_tae",
                name="preprocess_contratos_tae",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_additional_contratos_tae",
                outputs="int_additional_contratos_tae",
                name="preprocess_additional_contratos_tae",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_competitiveness_index",
                outputs="int_competitiveness_index",
                name="preprocess_competitiveness_index",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_maestro_data",
                outputs="int_maestro_data",
                name="preprocess_maestro_data",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_patentes",
                outputs="int_patentes",
                name="preprocess_patentes",
            ),
            node(
                func=preprocess_columns,
                inputs="raw_base_industrial",
                outputs="int_base_industrial",
                name="preprocess_base_industrial",
            ),
            node(
                func=process_base_tae_tct,
                inputs="int_base_tct_tae",
                outputs="prm_base_tct_tae",
                name="process_base_tct_tae",
            ),
            node(
                func=process_base_industrial,
                inputs="int_base_industrial",
                outputs="prm_base_industrial",
                name="process_base_industrial",
            ),
            node(
                func=process_base_cupon_electronico,
                inputs="int_base_cupon_electronico",
                outputs="prm_base_cupon_electronico",
                name="process_base_cupon_electronico",
            ),
            node(
                func=process_base_empresas,
                inputs="int_base_empresas",
                outputs="prm_base_empresas",
                name="process_base_empresas",
            ),
            node(
                func=process_maestro_data,
                inputs="int_maestro_data",
                outputs="prm_maestro_data",
                name="process_maestro_data",
            ),
            node(
                func=process_competitiveness_index,
                inputs="int_competitiveness_index",
                outputs="prm_competitiveness_index",
                name="process_competitiveness_index",
            ),
            node(
                func=create_clients_to_remove,
                inputs=[
                    "int_contratos_tae",
                    "int_contratos_tct",
                    "int_additional_contratos_tae",
                ],
                outputs="prm_clients_to_remove",
                name="create_clients_to_remove",
            ),
            node(
                func=create_master_transactions,
                inputs=[
                    "prm_base_tct_tae",
                    "prm_base_cupon_electronico",
                    "prm_maestro_data",
                    "prm_competitiveness_index",
                    "prm_clients_to_remove",
                ],
                outputs="mst_transactions",
                name="create_master_transactions",
            ),
            node(
                func=create_master_patentes,
                inputs=["mst_transactions", "int_patentes"],
                outputs="master_patentes",
                name="create_master_patentes",
            ),
            node(
                func=create_master_transactions_channel,
                inputs=["params:channel", "mst_transactions"],
                outputs="mst_transactions_channel",
                name="create_master_transactions_channel",
            ),
            node(
                func=create_spine_clientes,
                inputs=["mst_transactions_channel"],
                outputs="spine_clientes_channel",
                name="create_spine_clientes",
            ),
            node(
                func=create_master_year_channel_trx,
                inputs=["params:customer_master", "mst_transactions_channel"],
                outputs="master_year_channel_trx",
                name="create_master_year_channel_trx",
            ),
            node(
                func=create_master_year_network_trx,
                inputs=["params:customer_master", "mst_transactions"],
                outputs="master_year_network_C_trx",
                name="create_master_year_network_C_trx",
            ),
            node(
                func=create_master_year_region_channel_trx,
                inputs=[
                    "params:customer_master",
                    "mst_transactions_channel",
                    "master_year_channel_trx",
                ],
                outputs="master_year_region_channel_trx",
                name="create_master_year_region_channel_trx",
            ),
            node(
                func=create_master_monthly_tct_trx,
                inputs=["params:customer_master", "mst_transactions_channel"],
                outputs="master_month_tct_C_trx",
                name="create_master_month_tct_C_trx",
            ),
            node(
                func=create_master_yearly_station_tct_trx,
                inputs=["params:customer_master", "mst_transactions_channel"],
                outputs="master_yearly_station_tct_trx",
                name="create_master_yearly_station_tct_trx",
            ),
            node(
                func=create_master_trx_customer_tct,
                inputs=[
                    "spine_clientes_channel",
                    "master_year_channel_trx",
                    "master_year_region_channel_trx",
                    "master_month_tct_C_trx",
                    "master_patentes",
                    "master_yearly_station_tct_trx",
                    "master_year_network_C_trx",
                ],
                outputs="master_trx_customer_tct",
                name="create_master_trx_customer_tct",
            ),
            node(
                func=create_spine_clientes,
                inputs=[
                    "prm_base_industrial",
                ],
                outputs="spine_industrial",
                name="create_spine_industrial",
            ),
            node(
                func=create_master_total_industrial,
                inputs=[
                    "prm_base_industrial",
                ],
                outputs="master_total_industrial",
                name="create_master_total_industrial",
            ),
            node(
                func=create_master_planta_industrial,
                inputs=[
                    "prm_base_industrial",
                    "master_total_industrial",
                ],
                outputs="master_planta_industrial",
                name="create_master_planta_industrial",
            ),
            node(
                func=create_master_rubro_industrial,
                inputs=[
                    "prm_base_industrial",
                    "master_total_industrial",
                ],
                outputs="master_rubro_industrial",
                name="create_master_rubro_industrial",
            ),
            node(
                func=create_master_industrial,
                inputs=[
                    "spine_industrial",
                    "master_total_industrial",
                    "master_planta_industrial",
                    "master_rubro_industrial",
                ],
                outputs="master_industrial",
                name="create_master_industrial",
            ),
        ]
    )  # type: ignore
